# Generated by Django 5.2.2 on 2025-06-07 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_producto_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='tipo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('qr', 'QR'), ('credito', 'Crédito')], default='efectivo', max_length=20),
        ),
    ]
